In [1]:
import re
from gensim import models, corpora

In [1]:
from konlpy.tag import Okt
from collections import Counter
import pandas as pd

In [2]:
categ = pd.read_csv('C:/Users/Jae-Eun/Desktop/results/scene.csv',engine='python', encoding=' cp949')

In [5]:
categ.shape

(17, 61)

In [6]:
categ.head()

0                       1  \
0     id                       1   
1    num                    mult   
2   race                   Asian   
3  group              mult_Asian   
4     P1  오랜만에 지나가다가 헤어진 옛 연인 만남   

                                                   2  \
0                                                  9   
1                                               mult   
2                                              Asian   
3                                         mult_Asian   
4  남자가 여자를 짝사랑 하고 있는 것으로 보인다. 그러나 이를 표현할 수 없는 상황이...   

                                   3                                    4  \
0                                 21                                   26   
1                               mult                                 mult   
2                              Asian                                Asian   
3                         mult_Asian                           mult_Asian   
4  상대방의 말을 들으며 상대방의 진짜 속마음을 의심하고 있다.  친구들과 모처럼 밖에서 식사를 하며 친구와 대화를 나누고 있다.   

                                5                                6  \
0                              33                               43   
1                            mult                             mult   
2                           Asian                            Asian   
3                      mult_Asian                       mult_Asian   
4  날아오는 공을 잡기 위해 집중하고 있는 듯한 모습이다.  그냥 아무 생각 없이 물건을 집고 있는 상황으로 보인다.   

                                                   7  \
0                                                 46   
1                                               mult   
2                                              Asian   
3                                         mult_Asian   
4  딸들과 함께 샌드위치를 만들며 딸들이 하는 답답한 행동을 꾹 참으며 딸들과 놀아주고...   

                                                  8  \
0                                                54   
1                                              mult   
2                                             Asian   
3                                        mult_Asian   
4  가족 외식을 나왔지만 그닥 흥미롭지 않은 상황에 가만히 앉아 휴대전화만 쳐다보고 있다.   

                                                   9  ... Unnamed: 51  \
0                                                  6  ...          13   
1                                               mult  ...      filler   
2                                              Black  ...         NaN   
3                                         mult_Black  ...         NaN   
4  친구가 말이 되지 않는 말을 해 어이없고 한심해 보이는 표정이다. 현재 이 표정을 ...  ...         NaN   

  Unnamed: 52 Unnamed: 53 Unnamed: 54 Unnamed: 55 Unnamed: 56 Unnamed: 57  \
0          19          24          29          35          40          45   
1      filler      filler      filler      filler      filler      filler   
2         NaN         NaN         NaN         NaN         NaN         NaN   
3         NaN         NaN         NaN         NaN         NaN         NaN   
4         NaN         NaN         NaN         NaN         NaN         NaN   

  Unnamed: 58 Unnamed: 59 Unnamed: 60  
0          49          53          57  
1      filler      filler      filler  
2         NaN         NaN         NaN  
3         NaN         NaN         NaN  
4         NaN         NaN         NaN  

[5 rows x 61 columns]

In [3]:
print(categ.columns)
okt = Okt()

Index(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12',
       '13', '14', '15', '16', '17', '18', '19', '20', '21', '22', '23', '24',
       '25', '26', '27', '28', '29', '30', '31', '32', '33', '34', '35', '36',
       '37', '38', '39', '40', '41', '42', '43', '44', '45', '46', '47', '48',
       'Unnamed: 49', 'Unnamed: 50', 'Unnamed: 51', 'Unnamed: 52',
       'Unnamed: 53', 'Unnamed: 54', 'Unnamed: 55', 'Unnamed: 56',
       'Unnamed: 57', 'Unnamed: 58', 'Unnamed: 59', 'Unnamed: 60'],
      dtype='object')


In [4]:
def preprocessing(doc):
    morphs = []
    noun_adj_list=[]
    stopwords = ['하는','남', '감', '욕', '항', '움', '함', '스러', '계심','억', '중', '대감', '수','줄', '심', '로움','간', '있다', '있는',
             '상황', '모습', '사진','중이', '것','하고','같다', '하러', '해서','대해','있음', '할', '않아', '된', '뭔가', '이', '그', '못', 
              '해', '않은', '하며', '있는데','만','있어', '이기', '하고있다', '있지만', '듯', '스럽고', '했는데','않고', '하여', '되지','스럽다',
             '하다', '이를','하던','하면서','하려','고', '싶다','상치','하지','를','않는','거','치', '같음']
    for word in doc:
        morphs.append(okt.pos(word))
    for words in morphs:
        for word, tag in words:
            if tag in ['Noun','Adjective','Verb']:
                if word not in stopwords:
                    noun_adj_list.append(word)
    return noun_adj_list
    

In [5]:
doc1 = preprocessing(categ['1'])
doc2 = preprocessing(categ['2'])
doc3 = preprocessing(categ['3'])
doc4 = preprocessing(categ['4'])
doc5 = preprocessing(categ['5'])
doc6 = preprocessing(categ['6'])
doc7 = preprocessing(categ['7'])
doc8 = preprocessing(categ['8'])
doc25 = preprocessing(categ['25'])
doc26= preprocessing(categ['26'])
doc27 = preprocessing(categ['27'])
doc28 = preprocessing(categ['28'])
doc29 = preprocessing(categ['29'])
doc30 = preprocessing(categ['30'])
doc31 = preprocessing(categ['31'])
doc32 = preprocessing(categ['32'])

In [6]:
tokenized_data = [doc1, doc2, doc3, doc4, doc5, doc6, doc7, doc8, doc25, doc26, doc27, doc28, doc29, doc30, doc31, doc32]
print(tokenized_data)

[['지나가다가', '헤어진', '연인', '만남', '여자친구', '말', '행동', '실망', '했고', '차분하게', '따지는', '속', '매우', '불안하고', '짜증', '나', '표정', '드러내려고', '하지는', '여자친구', '어떤', '일', '당해서', '대신', '화나하는', '사랑', '연인', '힘든', '일로', '인해', '이별', '통보', '받고', '아픔', '느끼는', '비서', '운전기사', '마음', '들지', '않아서', '언짢아', '표정', '중요한', '약속', '잘', '차려입고', '나왔고', '어색한', '전', '연인', '모르는', '사람', '마주친', '친구', '이야기', '들어주고', '긍정', '이야기', '아닌', '남자', '여자', '호감', '느껴', '마음', '표현', '했지만', '여자', '대답', '선뜻', '안', '해주어', '남자', '심각하다', '연인', '의견', '맞지', '않아서', '살짝', '분노한', '양복', '차려입고', '머리', '정돈', '나왔는데', '연인', '실망', '느끼는', '그냥', '정장', '입고', '데이트', '가다가', '캡쳐', '화면', '썩', '마음', '들지', '얘기', '들었지만', '애써', '감정', '누르며', '침착하고', '담담하게', '받아들이려', '계속', '머릿속', '좋아하는', '여자', '생각', '마음', '두고', '있다가', '만나서', '진지한', '만남', '하자', '긴장', '떨리지만', '고백', '하려는', '장면'], ['남자', '여자', '짝사랑', '보인다', '표현', '없는', '쳐다만', '보고', '속', '남성은', '여성', '짝사랑', '상태', '그녀', '바로', '보는', '눈빛', '사랑', '느껴지지만', '막상', '여자', '별', '감정', '느끼지', '여자애', '연인', '사이', '아닌데', '보면서', '유혹', '당하고', '연인', '

In [11]:
dictionary = corpora.Dictionary(tokenized_data)

In [12]:
corpus = [dictionary.doc2bow(text) for text in tokenized_data]
print(corpus[4])

[(6, 1), (26, 1), (41, 3), (46, 1), (73, 1), (85, 1), (109, 1), (122, 1), (163, 6), (192, 2), (201, 2), (241, 1), (253, 1), (266, 1), (286, 1), (290, 1), (292, 1), (299, 1), (316, 1), (320, 1), (321, 1), (322, 7), (323, 1), (324, 1), (325, 1), (326, 1), (327, 1), (328, 1), (329, 1), (330, 1), (331, 1), (332, 1), (333, 1), (334, 1), (335, 1), (336, 1), (337, 1), (338, 1), (339, 1), (340, 1), (341, 1), (342, 1), (343, 1), (344, 1), (345, 1), (346, 1), (347, 1), (348, 1), (349, 1), (350, 1), (351, 1), (352, 1), (353, 1), (354, 2), (355, 1), (356, 1), (357, 1), (358, 1), (359, 1), (360, 1), (361, 1), (362, 1), (363, 1), (364, 2), (365, 1), (366, 1), (367, 1), (368, 1), (369, 1), (370, 1), (371, 2), (372, 1), (373, 1), (374, 2), (375, 1)]


In [22]:
NUM_TOPICS = 4

In [23]:
lda_model = models.LdaModel(corpus=corpus, num_topics=NUM_TOPICS, id2word=dictionary)

In [24]:
for idx in range(NUM_TOPICS):
    print("Topic #%s:" % idx, lda_model.print_topic(idx, 15))
print("=" * 20)

Topic #0: 0.021*"과일" + 0.009*"딸" + 0.008*"속" + 0.008*"마음" + 0.008*"아이" + 0.007*"생각" + 0.007*"느끼고" + 0.007*"친구" + 0.007*"경기" + 0.007*"집중" + 0.007*"상태" + 0.007*"자신" + 0.006*"인물" + 0.006*"요리" + 0.006*"일"
Topic #1: 0.012*"친구" + 0.011*"일" + 0.008*"집중" + 0.007*"속" + 0.007*"느끼고" + 0.007*"가족" + 0.007*"자신" + 0.007*"말" + 0.006*"당황" + 0.006*"이야기" + 0.006*"인물" + 0.006*"사람" + 0.006*"상태" + 0.005*"마음" + 0.005*"표정"
Topic #2: 0.011*"일" + 0.009*"마음" + 0.008*"서핑" + 0.008*"친구" + 0.008*"요리" + 0.007*"말" + 0.007*"속" + 0.007*"음식" + 0.006*"상태" + 0.006*"연인" + 0.005*"느끼고" + 0.005*"자신" + 0.005*"여자" + 0.005*"요리사" + 0.005*"없는"
Topic #3: 0.008*"속" + 0.008*"일" + 0.007*"말" + 0.007*"화가" + 0.006*"음식" + 0.006*"마음" + 0.006*"딸" + 0.006*"인물" + 0.006*"여자" + 0.005*"아이" + 0.005*"상태" + 0.005*"자신" + 0.005*"요리" + 0.005*"가게" + 0.005*"집중"


In [25]:
import pyLDAvis.gensim
pyLDAvis.enable_notebook()
vis = pyLDAvis.gensim.prepare(lda_model, corpus, dictionary)
pyLDAvis.display(vis)

In [7]:
from sklearn.decomposition import NMF, LatentDirichletAllocation, TruncatedSVD
from sklearn.feature_extraction.text import CountVectorizer

In [10]:
NUM_TOPICS = 5
lda_model = LatentDirichletAllocation(n_components=NUM_TOPICS, max_iter=10, learning_method='online')
lda_Z = lda_model.fit_transform(tokenized_data)
print(lda_Z.shape)



ValueError: Expected 2D array, got 1D array instead:
array=[list(['지나가다가', '헤어진', '연인', '만남', '여자친구', '말', '행동', '실망', '했고', '차분하게', '따지는', '속', '매우', '불안하고', '짜증', '나', '표정', '드러내려고', '하지는', '여자친구', '어떤', '일', '당해서', '대신', '화나하는', '사랑', '연인', '힘든', '일로', '인해', '이별', '통보', '받고', '아픔', '느끼는', '비서', '운전기사', '마음', '들지', '않아서', '언짢아', '표정', '중요한', '약속', '잘', '차려입고', '나왔고', '어색한', '전', '연인', '모르는', '사람', '마주친', '친구', '이야기', '들어주고', '긍정', '이야기', '아닌', '남자', '여자', '호감', '느껴', '마음', '표현', '했지만', '여자', '대답', '선뜻', '안', '해주어', '남자', '심각하다', '연인', '의견', '맞지', '않아서', '살짝', '분노한', '양복', '차려입고', '머리', '정돈', '나왔는데', '연인', '실망', '느끼는', '그냥', '정장', '입고', '데이트', '가다가', '캡쳐', '화면', '썩', '마음', '들지', '얘기', '들었지만', '애써', '감정', '누르며', '침착하고', '담담하게', '받아들이려', '계속', '머릿속', '좋아하는', '여자', '생각', '마음', '두고', '있다가', '만나서', '진지한', '만남', '하자', '긴장', '떨리지만', '고백', '하려는', '장면'])
 list(['남자', '여자', '짝사랑', '보인다', '표현', '없는', '쳐다만', '보고', '속', '남성은', '여성', '짝사랑', '상태', '그녀', '바로', '보는', '눈빛', '사랑', '느껴지지만', '막상', '여자', '별', '감정', '느끼지', '여자애', '연인', '사이', '아닌데', '보면서', '유혹', '당하고', '연인', '감정', '변한', '아닌지', '의심', '여자', '말', '남자', '듣지', '여자', '한번', '해보려고', '생각', '가득', '차있는', '공부', '일', '동료', '일', '지켜보고있다', '과제', '친구', '자신', '의견', '말', '친구', '말', '집중', '공부', '평소', '친하게', '지내던', '친구', '성적', '느껴졌다', '연인', '말', '의심스러운', '썸녀', '공부', '하재서', '나오긴', '나왔는데', '어떻게', '그녀', '옷', '벗길지만', '고민', '과외', '선생님', '설명', '하지만', '반해서', '몰래', '쳐다보는', '상대방', '반응', '대답', '큰', '기대', '기다리고', '남자', '잘못', '둘러', '핑계', '되지만', '여자', '알', '있다는', '식', '통달', '기분', '답', '남자', '속', '깜짝', '놀라며', '뭐라', '답'])
 list(['상대방', '말', '들으며', '상대방', '진짜', '속마음', '의심', '속', '인물', '모르는', '사람', '민폐', '행동', '화가', '났고', '따지는', '딸', '남자친구', '온', '아이', '보면서', '의심', '눈초리', '주는', '가족', '있던', '집', '불청객', '찾아와', '불청객', '대한', '혐오', '느끼고', '잇다', '막내', '딸', '미래', '남편', '집', '처음', '데리', '와', '딸', '아버지', '처음', '마주', '장면', '아버지', '아마', '마음', '들지', '아마', '결과', '안', '좋을', '직원', '한', '공간', '업무', '수행', '유심', '지켜보고', '속', '인물', '일', '얼굴', '낯', '익은데', '잘', '모르겠는', '사람', '자신', '보러', '나타나서', '살짝', '당황', '상태', '직원', '자신', '당하는', '부당', '대우', '항의', '논리', '화', '내서', '앞', '회사', '망할까봐', '겁나고', '초조하고', '막막하다', '앞', '앉아있는', '남자', '맘', '드는', '딸', '데려온', '못마땅하게', '관찰', '아버지', '남친', '소개', '받는', '자리', '신중하게', '스캔', '부하', '직원', '벌어진', '사건', '설명', '믿어지지가', '않음', '자식', '세명', '늦게', '집', '와서', '둘', '혼나고', '가장', '늦은', '아이', '어떻게', '혼내줄까', '고민', '장면'])
 list(['친구', '모처럼', '밖', '식사', '친구', '대화', '나누고', '차', '마시는', '도중', '갑자기', '찍자', '매우', '당혹스러운', '표정', '짓고', '그냥', '밥', '먹기', '전', '생각', '감정', '없는', '상태', '억지로', '찍어', '짜증', '느끼고', '친구', '카페', '갔는데', '옆', '친구', '아무', '말', '갑자기', '찍었다', '빨간', '박스', '사람', '평소', '잘', '찍지', '성격', '카페', '빵', '커피', '마시고', '별', '느낌', '없는', '표정', '짓고', '잇다', '친구', '티타임', '가지던', '친구', '말', '흥미', '느끼고', '친구', '느긋학하', '얘기', '도중', '친구', '찍으려', '카메라', '켰고', '카메라', '봤다', '친구', '갑자기', '찍어서', '놀란', '친구', '디저트', '먹으러', '왔는데', '하게', '카메라', '들이', '대서', '살짝', '놀란', '배고파서', '밥', '먹으려는데', '찍어서', '궁금함을', '갖고', '쳐다보는', '식사', '시간', '먹을', '생각', '별로', '없는', '동료', '별', '생각', '식사', '권함', '호텔', '조식', '시간', '합', '식사', '하는데', '갑자기', '찍어', '당황'])
 list(['날아오는', '공', '잡기', '위해', '집중', '처음', '본', '사람', '운동', '스릴', '느끼고', '개임', '싶어서', '승부', '집중', '운동', '지쳐', '피로', '느끼고', '피구', '시합', '나와', '옆', '친구', '둘', '남지', '않았다', '우리', '둘', '죽으면', '끝난다는', '명감', '집중', '체육관', '경기', '참여', '선수', '긴장감', '갖고', '경기', '집중', '친목', '다지기', '위', '농구', '경기', '속', '인물', '진지하게', '경기', '임', '체조', '배우고있다', '잘', '따라하려', '노력', '경기', '꼭', '이겨야겠다고', '집중', '지속', '경기', '지쳐', '피곤해서', '끝났으면', '좋겠는', '동료', '피구', '하는데', '집중', '경기', '공이', '넘어올', '순간', '긴장', '마음', '기다리고', '대학', '오리엔테이션', '친목', '도모', '춤추는', '다른', '사람', '틀려도', '별로', '개', '의치', '않지만', '빨간', '박스', '사람', '굉장히', '진지함'])
 list(['그냥', '아무', '생각', '물건', '집고', '보인다', '친구', '게임', '친구', '싶다는', '승부', '표정', '드러난다', '그냥', '아무런', '감정', '다른', '사람', '지켜보는', '여행', '가기전', '갖고', '기다리고', '은행', '할머니', '단체', '정부', '원금', '신청', '왔다', '큰일', '났다는', '표정', '게임', '같은', '어떤', '활동', '집중', '흥미', '느끼고', '속', '인물', '업무', '쉬는', '시간', '회사', '동료', '게임', '열정', '즐기고', '상태', '곧', '퇴근', '시간', '청소', '하면', '집', '가기', '때문', '후련한', '마음', '청소', '입국심사', '동료', '닌텐도', '게임', '한판', '이기겠다고', '각성', '직장', '동료', '회사', '쉬는시간', '닌텐도', '위', '집중', '숙소', '짐', '풀', '선수', '가벼운', '간이', '시합', '벌어져', '긴장', '들고', '흔들지만', '상대편', '눈치', '채지', '실망함'])
 list(['딸', '샌드위치', '만들며', '딸', '답답한', '행동', '꾹', '참으며', '딸', '놀아주고', '속', '엄마', '자신', '딸', '요리', '보고', '흐뭇해하고', '딸', '놀아주고', '정도', '지쳐하고', '입양', '딸', '행동', '보고', '사랑', '느끼고', '아이', '샌드위치', '스스로', '싸서', '먹는', '수업', '쏟지', '제대로', '지', '걱정', '조카', '모르는', '아이', '요리', '가르쳐주며', '잘', '따라오는지', '관심', '있게', '지켜보고있다', '요리', '가르치는', '속', '인물', '혹시', '아이', '음식', '쏟거나', '다칠까봐', '걱정스러워하며', '보고', '아이', '샌드위치', '만드는', '법', '알려주는', '아이', '막무가내', '불만족', '아이', '음식', '담는', '지켜보는', '입양', '아기', '데리', '요리', '교실', '열었는데', '생각', '호기심', '보이는', '딸', '음식', '만드는것을', '옆', '집중', '가르쳐', '주며', '확인', '딸', '식사', '차려', '보는', '견', '조심스러운', '마음', '지켜보는', '엄마', '아이', '샌드위치', '만들어', '먹겠', '다해', '엄마', '불안하게', '지켜보는'])
 list(['가족', '외식', '나왔지만', '그닥', '흥미롭지', '앉아', '휴대전화', '쳐다보고', '속', '인물', '매일', '만나는', '친구', '그렇기에', '속', '인물', '휴대폰', '지루함', '느끼고', '그냥', '따른', '감정', '밥', '먹고', '쉬는', '가족', '모임', '억지로', '참가', '하게', '되어', '지루함', '느끼는', '외식', '갔는데', '아무', '말', '핸드폰', '잡고', '보고', '가족', '식사', '나왔지만', '음식', '나오지', '각자', '무료', '하게', '핸드폰', '사촌', '만나', '어색함에', '말', '없어', '들', '핸드폰', '보고', '상태', '망', '가족', '외식', '가족', '말', '없고', '핸드폰', '본다', '가족', '식사', '가족', '외식', '나왔다가', '모두', '폰', '보고있어서', '지겨운', '가족', '식사', '음식', '나와서', '지루해', '가족', '외식', '나왔지만', '원하던', '바', '아니라', '재미없고', '지루함', '여행', '카페', '쉬', '차분하게', '핸드폰'])
 list(['직장', '상사', '비난', '받은', '후', '화가', '나', '상사', '때문', '표', '출하', '보인다', '자신', '계획', '했던', '헛수고', '돌아가자', '실망', '올라오고', '동시', '화가', '나있는', '상태', '직장', '동료', '보는데', '한심하게', '보는', '동료', '행동', '보며', '부러워하고', '질투', '학생', '회사', '낮은', '지위', '사람', '불만', '가득', '차', '말', '정장', '갖춰', '입고', '회사', '왔는데', '누군가', '마음', '들지', '일', '벌이', '속', '인물', '선생님', '학생', '예의', '없는', '행동', '의해', '화가', '살짝', '난', '상태', '퇴근', '하려는데', '상사', '일', '또', '줬다', '부하', '직원', '무엇', '일', '잘못', '화가', '난', '차', '가지러', '주차장', '왔는데', '차가', '도난', '직장', '자꾸', '누가', '갈궈서', '매우', '빡친', '마음', '들지', '사실', '통보', '받았거나', '깨', '달아서', '우울한', '상념', '사로잡힘', '화가', '나있는', '상태', '상대방', '만나', '그래', '설명', '들어', '보자'])
 list(['누군가', '대화', '당황', '표정', '전혀', '숨기', '자신', '예상', '이야기', '누군가', '로부터', '전해', '듣고', '충격', '받은', '상태', '소개팅', '자리', '소개팅', '말', '당황', '소개팅', '자리', '설레는', '사람', '만났다', '맞선', '자리', '나왔는데', '상대로', '나온', '남자', '마음', '들지', '여자', '집', '가고', '싶다는', '생각', '머릿속', '가득하다', '중요한', '미팅', '만남', '긴장', '친하지', '친구', '차', '마시면서', '이야기', '나누다가', '살짝', '당황', '이야기', '듣는', '남자친구', '엄마', '만났는데', '자신', '경멸', '말투', '얘기', '약속', '예쁘게', '꾸미고', '나왔는데', '상대', '없는', '예쁘게', '차려입고', '나와서', '이야기', '듣고', '놀란', '까페', '소개팅', '대상', '이야기', '듣는', '보통', '감정', '얘기', '듣고', '다소', '놀라면서도', '침착', '유지', '남자친구', '만나', '지난날', '얘기', '옛날', '잘못', '일', '얘기', '허탈해'])
 list(['어떤', '일', '도', '모함', '상기', '속', '인물', '현재', '믿을', '없을', '정도', '충격', '말', '들었다', '무얼', '결과', '나와서', '당황', '무언가', '보며', '미래', '자신', '행동', '다짐', '새로운', '무언가', '보고', '그것', '해보고', '싶은', '호기심', '가득', '찬', '표정', '사부', '앞', '계실', '같고', '새로운', '장비', '보여주고', '있을', '방', '누군가', '기다리고', '누군가', '들어와', '사람', '기대하고', '선배', '대화', '일', '제의', '받아', '당황', '사귄', '여자친구', '결혼', '하자고', '여자친구', '자신', '결혼', '목적', '만난', '전혀', '아니라고', '황당', '어이', '없다', '무엇', '놀라운', '장면', '본', '놀라운', '사실', '마주', '사부', '소식', '듣고', '조금', '놀라는', '주위', '불쾌하고', '이해', '없는', '일어나', '파악', '막중', '일', '해결', '하려고', '왔지만', '실망', '당혹스러워'])
 list(['오븐', '그릇', '빼며', '요리', '온전히', '집중', '자신', '정성껏', '한', '요리', '기대', '오븐', '꺼내고', '그냥', '뭐', '만들고', '감정', '느끼고', '음식', '꺼내면서', '느끼고', '저녁', '먹기', '위해', '된장찌개', '끓였다', '꺼내서', '먹고', '오븐', '요리', '꺼내며', '잘', '되었는지', '갖고', '살펴보고', '전자레인지', '음식', '돌렸는데', '음식', '예상', '다르게', '이상하게', '되어서', '당황', '빵', '구었다', '일단', '비주', '얼', '괜찮아서', '기분', '좋다', '맛', '괜찮을지', '몰라서', '긴장', '된다', '오븐', '무엇', '꺼내는', '새벽', '배고파서', '계란찜', '데워서', '꺼내는데', '다소', '흥분', '되는', '음식', '되었나', '궁금함을', '갖고', '조마조마하며', '보고있는', '뜨거운', '요리', '데이지', '않도록', '조심스러운', '마음', '전자레인지', '음식', '넣음', '전자렌지', '음식', '전혀', '조리', '안되어', '실망하는'])
 list(['좋아하는', '스포츠인', '서핑', '바다', '와', '들떠있는', '자신', '좋아하는', '취미', '생활', '행복', '느끼고', '하루', '종일', '재밌는', '서핑', '하루', '만족해하는', '여유', '장면', '서핑', '즐기고', '나와', '해방', '느끼고', '시험', '끝나고', '좋아하는', '서핑', '바다', '갔다', '이제', '바다로', '막', '들어가려는', '참이다', '본인', '실력', '뽐내기', '위해', '자랑스러운', '마음', '서핑', '나가는', '속', '인물', '무거운', '보드', '들고', '바닷가', '걷느라', '힘든', '상태', '방학', '맞이', '근처', '바닷가', '와서', '서핑', '바다', '서핑보드', '타는', '처음', '서핑', '나와서', '기대되', '행복한', '서핑', '들어가기', '전', '인증샷', '찍는', '즐거워', '하는것을', '볼', '익숙한', '서핑', '즐기기', '위해', '제나', '침착한', '준비', '서핑', '마치', '즐겁게', '가고'])
 list(['과일', '가게', '장사', '생계', '걱정스러운', '주인', '아주머니', '오늘', '벌어', '들인', '수익', '보면서', '앞', '앞날', '걱정', '그냥', '과일', '가게', '직원', '일', '딱히', '감정', '있지', '장면', '마트', '업무', '지쳐', '피로', '느끼고', '저녁', '거리', '사러', '마트', '왔는데', '아이', '입', '짧아서', '무엇', '사서', '저녁', '차려줄지', '고민', '가게', '보며', '특별히', '일', '무료', '하루', '보내고', '과일', '가게', '속', '인물', '손님', '많지', '않아서', '지루해하고', '상태', '가게', '마감', '시간', '집중', '하루', '매출', '계산', '장사', '잘', '안되는', '과일', '가게', '일', '아주머니', '조금', '더워서', '짜증난', '주인', '아주머니', '무료', '하게', '일', '늘', '해온', '가게', '일', '오늘', '변함', '지루하지만', '성실한', '마음', '해나', '매일', '똑같은', '상속', '지치고', '힘든', '장사', '하루하루', '연명', '살아감'])
 list(['주방', '주문', '밀려', '밀린', '일', '처리', '속', '요리사', '자신', '요리', '불만족', '요리사', '일', '하다가', '힘들어하고', '지쳐하는', '표정', '부하', '주방', '업무', '마음', '들지', '화가', '나', '갑자기', '저녁', '시간', '단체', '손님', '예약', '찾아와', '주방', '큰', '튀김', '음식', '시켜', '해야', '부담', '느낌', '요리사', '로서', '집중', '열정', '일', '속', '인물', '식당', '일', '요리사', '주문', '들어와서', '힘들어하고', '상태', '튀김', '기름', '건져', '야하는', '시간', '엄수', '중요하기', '때문', '혹시', '튀김', '늦게', '꺼내서', '맛', '없어질까', '긴장', '바쁜', '레스토랑', '일', '요리사', '요리', '불', '세서', '불만', '요리', '감자', '튀김', '튀기는데', '열기', '강하고', '기름', '튈까봐', '조심하며', '걱정', '준비', '둔', '요리', '재료', '도구', '제', '자리', '없어서', '짜증', '곱절', '치솟음', '설거지', '부탁', '하였지만', '통', '설거지', '보고', '화가'])
 list(['가족', '먹고', '한', '과일', '사가고', '싶지만', '당장', '돈', '없어', '구매', '없는', '아버지', '속상함이', '담겨있다', '과일', '장수', '자신', '파는', '과일', '상태', '그리', '좋지', '하다는', '인지', '매우', '실망', '그냥', '과일', '고르고', '손님', '아무런', '감정', '느끼지', '자신', '과일', '품질', '마음', '들지', '불만', '생기는', '매일', '과일', '다듬는', '과정', '매일', '일이', '만큼', '지루함', '느끼고', '일', '끝내고', '싶다는', '생각', '없다', '트럭', '귤', '파는', '장사꾼', '평소', '장사', '무료함', '느낀다', '과일', '장수인', '속', '인물', '많은', '과일', '언제', '팔지', '막막해하고', '귤', '장사', '아저씨', '귤', '상태', '보고', '버려야하나', '팔', '있나', '고민', '과일', '팔리는', '과일', '고르는데', '들고', '있는게', '나쁘지', '않다고', '생각', '무', '감정', '과일', '장수', '아저씨', '손님', '기다리는', '트럭', '파는', '과일', '조심스러운', '마음', '살펴봄', '많은', '걸', '언제', '파', '실망', '걱정', '됨'])].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [11]:
help(lda_model.fit_transform)

Help on method fit_transform in module sklearn.base:

fit_transform(X, y=None, **fit_params) method of sklearn.decomposition._lda.LatentDirichletAllocation instance
    Fit to data, then transform it.
    
    Fits transformer to X and y with optional parameters fit_params
    and returns a transformed version of X.
    
    Parameters
    ----------
    X : numpy array of shape [n_samples, n_features]
        Training set.
    
    y : numpy array of shape [n_samples]
        Target values.
    
    **fit_params : dict
        Additional fit parameters.
    
    Returns
    -------
    X_new : numpy array of shape [n_samples, n_features_new]
        Transformed array.



In [14]:
token = pd.DataFrame(tokenized_data)

token.head()

0    1    2    3     4    5    6   7    8     9    ...   119   120   121  \
0  지나가다가  헤어진   연인   만남  여자친구    말   행동  실망   했고  차분하게  ...    고백   하려는    장면   
1     남자   여자  짝사랑  보인다    표현   없는  쳐다만  보고    속   남성은  ...  None  None  None   
2    상대방    말  들으며  상대방    진짜  속마음   의심   속   인물   모르는  ...    와서     둘   혼나고   
3     친구  모처럼    밖   식사    친구   대화  나누고   차  마시는    도중  ...  None  None  None   
4   날아오는    공   잡기   위해    집중   처음    본  사람   운동    스릴  ...  None  None  None   

    122   123   124   125   126   127   128  
0  None  None  None  None  None  None  None  
1  None  None  None  None  None  None  None  
2    가장    늦은    아이   어떻게  혼내줄까    고민    장면  
3  None  None  None  None  None  None  None  
4  None  None  None  None  None  None  None  

[5 rows x 129 columns]

In [16]:
detokenized_doc = []
for doc in tokenized_data:
    t = ' '.join(doc)
    detokenized_doc.append(t)

print(detokenized_doc[:5])

['지나가다가 헤어진 연인 만남 여자친구 말 행동 실망 했고 차분하게 따지는 속 매우 불안하고 짜증 나 표정 드러내려고 하지는 여자친구 어떤 일 당해서 대신 화나하는 사랑 연인 힘든 일로 인해 이별 통보 받고 아픔 느끼는 비서 운전기사 마음 들지 않아서 언짢아 표정 중요한 약속 잘 차려입고 나왔고 어색한 전 연인 모르는 사람 마주친 친구 이야기 들어주고 긍정 이야기 아닌 남자 여자 호감 느껴 마음 표현 했지만 여자 대답 선뜻 안 해주어 남자 심각하다 연인 의견 맞지 않아서 살짝 분노한 양복 차려입고 머리 정돈 나왔는데 연인 실망 느끼는 그냥 정장 입고 데이트 가다가 캡쳐 화면 썩 마음 들지 얘기 들었지만 애써 감정 누르며 침착하고 담담하게 받아들이려 계속 머릿속 좋아하는 여자 생각 마음 두고 있다가 만나서 진지한 만남 하자 긴장 떨리지만 고백 하려는 장면', '남자 여자 짝사랑 보인다 표현 없는 쳐다만 보고 속 남성은 여성 짝사랑 상태 그녀 바로 보는 눈빛 사랑 느껴지지만 막상 여자 별 감정 느끼지 여자애 연인 사이 아닌데 보면서 유혹 당하고 연인 감정 변한 아닌지 의심 여자 말 남자 듣지 여자 한번 해보려고 생각 가득 차있는 공부 일 동료 일 지켜보고있다 과제 친구 자신 의견 말 친구 말 집중 공부 평소 친하게 지내던 친구 성적 느껴졌다 연인 말 의심스러운 썸녀 공부 하재서 나오긴 나왔는데 어떻게 그녀 옷 벗길지만 고민 과외 선생님 설명 하지만 반해서 몰래 쳐다보는 상대방 반응 대답 큰 기대 기다리고 남자 잘못 둘러 핑계 되지만 여자 알 있다는 식 통달 기분 답 남자 속 깜짝 놀라며 뭐라 답', '상대방 말 들으며 상대방 진짜 속마음 의심 속 인물 모르는 사람 민폐 행동 화가 났고 따지는 딸 남자친구 온 아이 보면서 의심 눈초리 주는 가족 있던 집 불청객 찾아와 불청객 대한 혐오 느끼고 잇다 막내 딸 미래 남편 집 처음 데리 와 딸 아버지 처음 마주 장면 아버지 아마 마음 들지 아마 결과 안 좋을 직원 한 공간 업무 수행 유심 지켜보고 속 인물 일 얼굴 낯 

In [17]:
detok=pd.DataFrame(detokenized_doc)
detok.head()

0
0  지나가다가 헤어진 연인 만남 여자친구 말 행동 실망 했고 차분하게 따지는 속 매우 ...
1  남자 여자 짝사랑 보인다 표현 없는 쳐다만 보고 속 남성은 여성 짝사랑 상태 그녀 ...
2  상대방 말 들으며 상대방 진짜 속마음 의심 속 인물 모르는 사람 민폐 행동 화가 났...
3  친구 모처럼 밖 식사 친구 대화 나누고 차 마시는 도중 갑자기 찍자 매우 당혹스러운...
4  날아오는 공 잡기 위해 집중 처음 본 사람 운동 스릴 느끼고 개임 싶어서 승부 집중...

In [21]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer(stop_words='english', max_features=1000)
X = vectorizer.fit_transform(detok[0])

In [29]:
from sklearn.decomposition import LatentDirichletAllocation
lda_model = LatentDirichletAllocation(n_components=15, learning_method='online', random_state=777, max_iter=1)
lda_top = lda_model.fit_transform(X)
print(lda_model.components_)
print(lda_model.components_.shape)

[[0.78565627 0.75808915 0.91904136 ... 0.74581956 0.88384806 0.72559238]
 [0.87396269 0.84912205 1.01803162 ... 0.72658161 1.02777015 0.80887337]
 [0.93156324 0.84834978 0.70523977 ... 0.8151036  0.76078553 0.88136926]
 ...
 [0.87286915 0.74963441 0.94541021 ... 0.8333161  0.75230196 0.94587099]
 [0.82288632 0.78850838 0.72773664 ... 0.62049089 0.69253182 0.63726324]
 [0.90385161 0.7406068  0.72191205 ... 0.95875901 0.90094969 0.83009276]]
(15, 815)


In [30]:
terms = vectorizer.get_feature_names() 
# 단어 집합. 1,000개의 단어가 저장되어있음.
def get_topics(components, feature_names, n=5):
    for idx, topic in enumerate(components):
        print("Topic %d :" % (idx+1), [(feature_names[i], topic[i].round(2)) for i in topic.argsort()[:-n -1:-1]])
get_topics(lda_model.components_, terms)

Topic 1 : [('친구', 1.25), ('속마음', 1.14), ('행동', 1.13), ('믿어지지가', 1.12), ('운동', 1.08)]
Topic 2 : [('상속', 1.09), ('아이', 1.09), ('전자렌지', 1.09), ('앉아', 1.07), ('짓고', 1.06)]
Topic 3 : [('표정', 1.07), ('진지한', 1.06), ('황당', 1.06), ('긍정', 1.05), ('왔지만', 1.05)]
Topic 4 : [('보통', 1.06), ('카페', 1.03), ('주차장', 1.03), ('차려', 1.03), ('들고', 1.02)]
Topic 5 : [('가르치는', 1.1), ('가르쳐', 1.07), ('하게', 1.05), ('디저트', 1.04), ('주며', 1.03)]
Topic 6 : [('당해서', 1.13), ('신중하게', 1.05), ('민폐', 1.05), ('느껴졌다', 1.04), ('찾아와', 1.04)]
Topic 7 : [('결과', 1.1), ('연인', 1.06), ('보면서', 1.06), ('막중', 1.05), ('쉬는시간', 1.05)]
Topic 8 : [('침착하고', 1.14), ('늦은', 1.11), ('사서', 1.08), ('정부', 1.06), ('수업', 1.05)]
Topic 9 : [('혼내줄까', 1.1), ('모처럼', 1.06), ('담겨있다', 1.05), ('걱정스러운', 1.05), ('속상함이', 1.04)]
Topic 10 : [('언짢아', 1.14), ('싸서', 1.1), ('쉬는', 1.09), ('나오긴', 1.08), ('다해', 1.08)]
Topic 11 : [('사실', 1.12), ('당황', 1.12), ('하는것을', 1.07), ('막내', 1.04), ('끝나고', 1.04)]
Topic 12 : [('재료', 1.13), ('닌텐도', 1.07), ('오븐', 1.06), ('조마조마하며', 1.05),

In [31]:
import pyLDAvis.sklearn
 
pyLDAvis.enable_notebook()
panel = pyLDAvis.sklearn.prepare(lda_model, X, vectorizer, mds='tsne')
panel

PreparedData(topic_coordinates=                x           y  topics  cluster       Freq
topic                                                    
0      114.344879  114.308296       1        1  17.671077
11     105.821045  -93.749626       2        1  11.324494
1     -138.334473   95.320763       3        1   9.889143
12      -7.436697  111.259697       4        1   8.008434
2     -207.550629 -105.472603       5        1   7.831227
6       52.817650   14.603765       6        1   7.215877
9      168.010849    6.806950       7        1   6.930554
5      -94.169601 -157.789551       8        1   6.197725
14    -122.849174  -39.059418       9        1   6.195129
7      -94.894264  195.408295      10        1   6.077054
8       24.927401 -180.464874      11        1   5.244368
3      -53.413467   26.832108      12        1   4.971742
13     -12.255850  -72.093201      13        1   0.814392
10    -224.217957   28.070581      14        1   0.814392
4       36.154255  209.427582      15        1   0.814392, topic_info=      Term      Freq     Total Category  logprob  loglift
240   레스토랑  0.000000  0.000000  Default  30.0000  30.0000
349     보드  0.000000  0.000000  Default  29.0000  29.0000
749     하게  0.000000  0.000000  Default  28.0000  28.0000
526     열정  0.000000  0.000000  Default  27.0000  27.0000
252     막내  0.000000  0.000000  Default  26.0000  26.0000
..     ...       ...       ...      ...      ...      ...
324    반해서  0.001368  0.142661  Topic15  -6.5259   0.1636
481    안되어  0.001377  0.144981  Topic15  -6.5197   0.1536
808  흐뭇해하고  0.001381  0.145885  Topic15  -6.5168   0.1503
194     도모  0.001375  0.144832  Topic15  -6.5212   0.1532
430   속상함이  0.001370  0.148566  Topic15  -6.5243   0.1246

[617 rows x 6 columns], token_table=Empty DataFrame
Columns: [Topic, Freq, Term]
Index: [], R=30, lambda_step=0.01, plot_opts={'xlab': 'PC1', 'ylab': 'PC2'}, topic_order=[1, 12, 2, 13, 3, 7, 10, 6, 15, 8, 9, 4, 14, 11, 5])